name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - uses: actions/checkout@v7
    - uses: hashicorp/setup-terraform@v4
    - name: Azure login
      uses: azure/login@v3
      with:
        client-id: 7f95b0e5-50c1-4c21-b58c-4fb245bacffd
        tenant-id: a2e466aa-4f86-4545-b5b8-97da7c8febf3
        subscription-id: 5e683e0f-b00c-48d6-9769-5aaf598de8f1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init 

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color -input=false -detailed-exitcode
        exit_code=$?
        if [ $exit_code -eq 2 ]; then
          echo "Changement de plan !! Cependant ok, pas erreur"
        elif [ $exit_code -ne 0 ]; then
          echo "erreur !!! erreur !!!! code de sortie $exit_code !!!!!"
          exit $exit_code
        fi
    
    - name: Terraform Destroy
      run: terraform destroy -auto-approve

    - name: Terraform Apply
      run: terraform apply -auto-approve