name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  Planifier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - uses: actions/checkout@v7
    - uses: hashicorp/setup-terraform@v4
    - name: Azure login
      uses: azure/login@v3
      with:
        client-id: ${{ vars.CLIENT_ID }}
        tenant-id: ${{ vars.TENANT_ID }}
        subscription-id: ${{ vars.SUBSCRIPTION_ID }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init 

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color -input=false -detailed-exitcode
        exit_code=$?
        if [ $exit_code -eq 2 ]; then
          echo "Changement de plan !! Cependant ok, pas erreur"
        elif [ $exit_code -ne 0 ]; then
          echo "erreur !!! erreur !!!! code de sortie $exit_code !!!!!"
          exit $exit_code
        fi
    
  Appliquer:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    needs: Planifier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - uses: actions/checkout@v7
    - uses: hashicorp/setup-terraform@v4
    - name: Azure login
      uses: azure/login@v3
      with:
        client-id: ${{ vars.CLIENT_ID }}
        tenant-id: ${{ vars.TENANT_ID }}
        subscription-id: ${{ vars.SUBSCRIPTION_ID }}
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Destroy
      run: terraform destroy -auto-approve

    - name: Terraform Apply
      run: terraform apply -auto-approve